{
 "title": "Ecovillage Passive Houses",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "Sensors",
    "query": "show tag values with key = displayName"
   }
  ]
 },
 "panels": [
  { "title": "Temperatures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Indoor temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EnvironmentalData",
     "select": [
      [
       { "params": [ "t" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.8 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "displayKey", "operator": "=~", "value": "/indoor/" },
      { "condition": "AND", "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Outdoor Temperatures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EnvironmentalData",
     "select": [
      [
       { "params": [ "t" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.8 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "devID", "operator": "=~", "value": "/outdoor/" }
     ]
    }
   ]
  },
  { "title": "Dewpoint", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Indoor dewpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EnvironmentalData",
     "select": [
      [
       { "params": [ "tDew" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.8 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "displayKey", "operator": "=~", "value": "/indoor/" },
      { "condition": "AND", "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Outdoor Dewpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EnvironmentalData",
     "select": [
      [
       { "params": [ "tDew" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 1.8 + 32" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "devID", "operator": "=~", "value": "/outdoor/" }
     ]
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Indoor Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EnvironmentalData",
     "select": [
      [
       { "params": [ "rh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devID", "operator": "=~", "value": "/indoor/" },
      { "condition": "AND", "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
     ]
    }
   ]
  },
  {
   "title": "Outdoor Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "EnvironmentalData",
     "select": [
      [
       { "params": [ "rh" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "devID", "operator": "=~", "value": "/outdoor/" }
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Indoor light",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "Wm2" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "EnvironmentalData",
       "select": [
        [
         { "params": [ "irradiance.IR" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "devID", "operator": "=~", "value": "/indoor/" },
        { "condition": "AND", "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "Outdoor light",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "Wm2" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "EnvironmentalData",
       "select": [
        [
         { "params": [ "irradiance.IR" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "devID", "operator": "=~", "value": "/outdoor/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Electricity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Grid Consumption (production)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Electricity",
     "select": [
      [
       { "params": [ "mainDemand" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=~", "value": "/[13]: Grid/" }
     ]
    },
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Electricity",
     "select": [
      [
       { "params": [ "mainDemand" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=~", "value": "/2: Grid/" }
     ]
    }
   ]
  },
  {
   "title": "Solar Production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Electricity",
     "select": [
      [
       { "params": [ "mainDemand" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=~", "value": "/Solar/" }
     ]
    }
   ]
  },
  { "title": "Raw Energy Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Energy Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "devID" ], "type": "tag" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Electricity",
     "select": [
      [
       { "params": [ "energySourced" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=~", "value": "/[13]: Grid/" }
     ]
    },
    {
     "alias": "$tag_displayName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "displayName" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Electricity",
     "select": [
      [
       { "params": [ "energyUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=~", "value": "/2: Grid/" }
     ]
    }
   ]
  },
  {
   "title": "Energy sourced",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "alias": "$tag_devID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "devID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Electricity",
     "select": [
      [
       { "params": [ "energyUsed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=~", "value": "/1: Grid/" }
     ]
    },
    {
     "alias": "$tag_devID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "devID" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Electricity",
     "select": [
      [
       { "params": [ "energySourced" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "displayName", "operator": "=~", "value": "/2: Grid/" }
     ]
    }
   ]
  },
  {
   "title": "Device Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSSI",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RFdata",
       "select": [
        [
         { "params": [ "rssi" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "SNR",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 39 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RFdata",
       "select": [
        [
         { "params": [ "snr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "RSSI by channel",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "alias": "Ch.$tag_channel",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "channel" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RFdata",
       "select": [
        [
         { "params": [ "rssi" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "SNR by channel",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 39 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "alias": "$tag_channel",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "channel" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RFdata",
       "select": [
        [
         { "params": [ "snr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "Spreading Factor",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RFdata",
       "select": [
        [
         { "params": [ "spreadingFactor" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "Bandwidth",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 47 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RFdata",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "*1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "Battery",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "EnvironmentalData",
       "select": [
        [
         { "params": [ "Vbat" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    },
    {
     "title": "Uplink count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 47 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_displayName",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "displayName" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "RFdata",
       "select": [
        [
         { "params": [ "counter" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "displayName", "operator": "=~", "value": "/^$Sensors$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}